apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commons
  labels:
    app: e-commons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commons
    spec:
      containers:
      - name: e-commons
        image: sakthibalan/e-commons:1.0
        ports:
        - containerPort: 8090
apiVersion: v1
kind: Service
metadata:
  name: e-commons
spec:
  ports:
  - port: 8090
    protocol: TCP
    nodePort: 30011
  selector:
    app: e-commons
  type: NodePort