apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commons
  labels:
    app: e-commons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commons
  template:
    metadata:
      labels:
        app: e-commons
    spec:
      containers:
      - name: e-commons
        image: sakthibalan/e-commons:1.0
        ports:
        - containerPort: 8080
apiVersion: v1
kind: Service
metadata:
  name: e-commons
  labels:
    app: e-commons
    spring-boot: "true"
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: e-commons
  type: NodePort